<?php

/**
 * @file
 * Render a Streaming Audio Player as a Drupal Field Type.
 */


/**
 * Implements hook_theme().
 */
function audio_streaming_player_theme($existing, $type, $theme, $path) {
  $hola = 1;
  return [
    'audio_streaming_player_black' => [
      'variables' => ['test_var' => NULL],
    ],
    'audio_streaming_player_circular' => [
      'variables' => ['test_var' => NULL],
    ],
    'audio_streaming_player_text' => [
      'variables' => ['test_var' => NULL],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function audio_streaming_player_preprocess_field(&$variables) {
  $element = $variables['element'];

  if ($element['#field_type'] == 'audio_streaming_player_type') {
    $link_value = $element['#items']->getValue()[0]['url'];
    $skin_value = $element['#items']->getValue()[0]['skin'];
    $autoplay_value = $element['#items']->getValue()[0]['autoplay'];

    $data_value_field =  [
      'data_value_field' => [
        'url' => $link_value,
        'skin' => $skin_value,
        'autoplay' => $autoplay_value,
      ],
    ];

    $variables['#attached']['drupalSettings']['data_value_field'] = $data_value_field['data_value_field'];
  }
}

